sudo: required
services:
  - docker

before_install:
  - docker build -t pervezalam777/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pervezalam777/docker-react npm run test -- --coverage